Update data_utils.py due to numpy deprecation in NumPy 1.20
Changed because it used to break indicating Numpy attribute error as: 
AttributeError: module 'numpy' has no attribute 'float'.

#See the error here:
[INFO: inference.py:  217]: Axial inference on /net/pnap/data/rd/testpatient_xxx/sub-xxxx_T1w.nii.gz finished in 97.8456 seconds
Traceback (most recent call last):
  File "/home/amit3/0Software/FastSurfer-2.0.0/FastSurferCNN/run_prediction.py", line 376, in <module>
    pred_data = eval.get_prediction(orig_fn, data_array, orig_img.header.get_zooms())
  File "/home/amit3/0Software/FastSurfer-2.0.0/FastSurferCNN/run_prediction.py", line 221, in get_prediction
    pred_classes = du.split_cortex_labels(pred_classes.cpu().numpy())
  File "/home/amit3/0Software/FastSurfer-2.0.0/FastSurferCNN/data_loader/data_utils.py", line 441, in split_cortex_labels
    aseg_lh = filters.gaussian_filter(1000 * np.asarray(aparc == 2, dtype=np.float), sigma=3)
  File "/home/amit3/0Software/anaconda3/envs/M2Sv4/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations